# Generated by Django 5.1.5 on 2025-06-13 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('bateria', 'Batería Baja'), ('temperatura', 'Temperatura Alta'), ('error', 'Error de Sistema'), ('mantenimiento', 'Mantenimiento Requerido')], max_length=20)),
                ('descripcion', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('personas_detectadas', models.IntegerField(default=0)),
                ('tiempo_activo', models.IntegerField(default=0)),
                ('energia_consumida', models.FloatField(default=0.0)),
                ('distancia_recorrida', models.FloatField(default=0.0)),
                ('temperatura', models.FloatField(default=0.0)),
                ('humedad', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
