# Generated by Django 5.1.5 on 2025-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='mesero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
