# Generated by Django 5.1.5 on 2025-06-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_mesa_mesero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='mesero',
        ),
        migrations.AddField(
            model_name='mesa',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
